apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
    - host: api-test-vodafoneziggo.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test
                port: 
                  number: 80
  tls:
  - hosts:
    - api-test-vodafoneziggo.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/test:{image-tag}
        ports:
        - containerPort: 3000
